# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # or "air" for lighter look
title                    : "Muhammad Waqas – Academic Portfolio"
title_separator          : "-"
name                     : &name "Muhammad Waqas"
description              : &description "Muhammad Waqas – Computational Researcher specializing in simulation and analytical modelling of complex systems."
url                      : "https://waqasswati.github.io"
baseurl                  : "" 
repository               : "WaqasSwati/WaqasSwati.github.io"

# Site Author – sidebar
author:
  avatar           : "profile.jpg"               # put your profile photo in /images/profile.png
  name             : "Muhammad Waqas"
  pronouns         : "he/him"
  bio              : "Computational researcher | Ph.D. Computer Science (Ca’ Foscari University of Venice) | Finite-capacity multi-server queueing systems in cloud data centers"
  location         : "Venice, Italy"
  employer         : "Ca’ Foscari University of Venice"
  email            : "muhammad.waqas@unive.it" 

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=rCTdcLQAAAAJ&hl=en"
  orcid            : "https://orcid.org/0000-0001-6489-2819"
  researchgate     : "https://www.researchgate.net/profile/Muhammad-Waqas-63?ev=hdr_xprf"

  # Repositories and software development
  github           : "waqasswati"

  # Social media
  twitter          : "Waqas1swati"
  linkedin         : "muhammad-waqas-swati-18a574152"
  # you can add other networks if you want

# Publication Category – (headings used by the theme)
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  # optional social preview image filename
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false      

comments:
  provider               : false

atom_feed:
  hide                   : false     

# SEO Related (optional)
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing defaults
twitter:
  username               : &twitter "Waqas1swati"
facebook:
  username               :

social:
  type                   : Person
  name                   : "Muhammad Waqas"
  links:
    - "https://scholar.google.com/citations?user=rCTdcLQAAAAJ&hl=en"
    - "https://github.com/waqasswati"
    - "https://www.researchgate.net/profile/Muhammad-Waqas-63?ev=hdr_xprf"
    - "https://twitter.com/Waqas1swati"
    - "https://www.linkedin.com/in/muhammad-waqas-swati-18a574152/"
    - "https://orcid.org/0000-0001-6489-2819"

# Analytics (optional)
analytics:
  provider               :  false 

# Reading Files
include:
  - .htaccess
  - _pages
  - files

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults (controls layout of pages)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC 

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
